---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi-san
provisioner: iscsi.csi.k8s.io
parameters:
  resourcegroup: "abhib-santest-2-rg"
  sanname: "abhibtestsan"
  volumegroupname: "abhibtestvg1"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: false
